name: Pull Request
run-name: Pull Request Checks on ${{ github.head_ref }}

on:
  pull_request:

concurrency:
  group: pull-request-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Install Dependencies
        run: npm install --ignore-scripts
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
